[phases.setup]
nixPkgs = ["python310", "gcc", "binutils"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]

[start]
cmd = "python azul_inference_server.py --host 0.0.0.0 --port $PORT"
